### ISSUE TITLE
Support own namespaces

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#9]
I want to use my own code namespaces such as `Sitole\Api\Shop`, but now is there only one hardcoded namespace. (PSR-4 autoloader support)

Possible solution: Require endpoints to implements `IEndpoint` interface and then autoregister them via Nette SearchExtension.

cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole Implemented by https://github.com/baraja-core/structured-api/commit/70865743ce41b46e8f63b70bef7bc32f1a6eb9b5

All classes implementing interface `Baraja\StructuredApi\Endpoint` will be automatically registered by Search extension.

Current configuration:

```yaml
search:
   structuredApi:
      in: %appDir%/..
      files: ['*Endpoint.php']
      implements: Baraja\StructuredApi\Endpoint
      tags: ['structured-api-endpoint']
```

BaseEndpoint implements interface natively.

Thanks.
